version: "3.2"

services:
  cautionary-alerts-listener:
    image: cautionary-alerts-listener
    build:
      context: .
      dockerfile: CautionaryAlertsListener/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
        - SONAR_TOKEN=${SONAR_TOKEN}
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=entitycorex;Username=postgres;Password=mypassword
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  cautionary-alerts-listener-test:
    image: cautionary-alerts-listener-test
    build:
      context: .
      dockerfile: CautionaryAlertsListener.Tests/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
        - SONAR_TOKEN=${SONAR_TOKEN}
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
      - CONNECTION_STRING=Host=test-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
    links:
      - test-database
  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database.env
      
